import type { ItemConhecimento } from "./tipos";

export const baseConhecimento: ItemConhecimento[] = [
  {
    id: "geral_titulacao_conceito",
    modulo: "geral",
    topico: "Titulação",
    assunto: "titulacao",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulação?",
      "O que é uma titulção?",
      "O que significa análise volumétrica?",
    ],
    palavrasChave: [
      "titulação",
      "titulacao",
      "titulção",
      "titulcao",
      "análise volumétrica",
      "analise volumetrica",
      "método volumétrico",
      "metodo volumetrico",
    ],
    termosContexto: ["titulante", "titulado", "ponto de equivalência"],
    termosEvitar: [
      "curva ácido-base",
      "curva complexométrica",
      "indicador",
      "interferente",
    ],
    respostaCurta:
      "Titulação é um método analítico usado para determinar a quantidade ou concentração de uma substância por meio de uma reação química.",
    respostaCompleta:
      "Titulação é um método analítico em que uma solução de concentração conhecida é adicionada gradualmente à amostra até atingir uma condição relacionada à estequiometria da reação. O volume gasto permite determinar a quantidade ou concentração do analito.",
    prioridade: 10,
  },
  {
    id: "geral_titulante_conceito",
    modulo: "geral",
    topico: "Titulante",
    assunto: "titulante",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulante?",
      "Quem fica na bureta?",
      "O que é solução titulante?",
    ],
    palavrasChave: [
      "titulante",
      "solução titulante",
      "solucao titulante",
      "reagente de concentração conhecida",
      "quem fica na bureta",
    ],
    termosContexto: ["titulante", "volume adicionado"],
    termosEvitar: ["titulado", "analito", "edta especificamente"],
    respostaCurta:
      "Titulante é a solução adicionada durante a titulação, geralmente com concentração conhecida ou padronizada.",
    respostaCompleta:
      "O titulante é a solução adicionada progressivamente à amostra durante a titulação. Ele reage com o analito segundo uma relação estequiométrica conhecida, e o volume utilizado é usado para calcular a quantidade da espécie analisada.",
    prioridade: 10,
  },
  {
    id: "geral_analito_conceito",
    modulo: "geral",
    topico: "Analito",
    assunto: "analito",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é analito?",
      "O que está sendo medido?",
      "Qual é a espécie analisada?",
    ],
    palavrasChave: [
      "analito",
      "espécie analisada",
      "especie analisada",
      "substância analisada",
      "substancia analisada",
      "componente de interesse",
    ],
    termosContexto: ["analito", "amostra"],
    termosEvitar: ["titulante", "indicador", "interferente"],
    respostaCurta:
      "Analito é a espécie química cuja quantidade ou concentração se deseja determinar.",
    respostaCompleta:
      "O analito é o componente de interesse da amostra. Em uma titulação, sua quantidade é determinada a partir da reação com o titulante e da relação estequiométrica entre as espécies envolvidas.",
    prioridade: 10,
  },
  {
    id: "complexometria_edta_conceito",
    modulo: "complexometria",
    topico: "EDTA",
    assunto: "edta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é EDTA?",
      "O que é titulante EDTA?",
      "EDTA é o quê na complexometria?",
    ],
    palavrasChave: [
      "edta",
      "titulante edta",
      "agente quelante edta",
      "ligante edta",
      "ácido etilenodiaminotetracético",
      "acido etilenodiaminotetracetico",
    ],
    termosContexto: ["EDTA", "complexo metal–EDTA", "metal principal"],
    termosEvitar: [
      "complexante auxiliar",
      "ligante auxiliar",
      "amônia",
      "amonia",
      "mascarante",
      "indicador",
      "interferente",
    ],
    respostaCurta:
      "O EDTA é um ligante polidentado usado para formar complexos estáveis com íons metálicos.",
    respostaCompleta:
      "Em titulações complexométricas, o EDTA geralmente atua como titulante. Ele possui vários átomos doadores e forma complexos estáveis com muitos íons metálicos, normalmente em proporção molar 1:1.",
    prioridade: 10,
  },
  {
    id: "complexometria_ligante_auxiliar_conceito",
    modulo: "complexometria",
    topico: "Ligante auxiliar",
    assunto: "ligante_auxiliar",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é complexante auxiliar?",
      "O que seria um ligante auxiliar?",
      "O que é complexante secundário?",
    ],
    palavrasChave: [
      "complexante auxiliar",
      "ligante auxiliar",
      "agente auxiliar",
      "complexante secundário",
      "complexante secundario",
      "complexante de apoio",
      "amônia",
      "amonia",
      "nh3",
    ],
    termosContexto: [
      "complexante auxiliar",
      "ligante auxiliar",
      "α(M livre)",
      "denominador β",
      "Kf efetivo",
    ],
    termosEvitar: [
      "EDTA como titulante principal",
      "indicador",
      "mascarante",
      "interferente metálico",
    ],
    respostaCurta:
      "Complexante auxiliar é uma espécie que também se liga ao metal e altera sua disponibilidade para reagir com o EDTA.",
    respostaCompleta:
      "Um complexante auxiliar, também chamado de ligante auxiliar, é uma espécie que pode se ligar ao metal principal além do EDTA. Ele pode ajudar a manter o metal dissolvido, evitar precipitação ou controlar a concentração de metal livre. Porém, como também compete com o EDTA, pode alterar o Kf efetivo e precisa ser considerado no equilíbrio do sistema.",
    prioridade: 10,
  },
  {
    id: "complexometria_ligante_auxiliar_interpretacao",
    modulo: "complexometria",
    topico: "Ligante auxiliar",
    assunto: "ligante_auxiliar",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Por que se usa complexante auxiliar?",
      "Para que serve o ligante auxiliar?",
      "Por que usar amônia na complexometria?",
    ],
    palavrasChave: [
      "por que usa complexante auxiliar",
      "pq usa complexante auxiliar",
      "para que serve complexante auxiliar",
      "função do complexante auxiliar",
      "funcao do complexante auxiliar",
      "por que usar ligante auxiliar",
      "complexante auxiliar atrapalha",
    ],
    termosContexto: [
      "complexante auxiliar",
      "ligante auxiliar",
      "Kf efetivo",
      "denominador β",
      "α(M livre)",
      "precipitação",
    ],
    termosEvitar: [
      "Kf efetivo isolado",
      "EDTA como titulante",
      "indicador",
      "interferente metálico",
    ],
    respostaCurta:
      "Usa-se um complexante auxiliar para controlar a disponibilidade do metal e melhorar as condições da titulação.",
    respostaCompleta:
      "Um complexante auxiliar pode ser usado para manter o metal em solução, evitar precipitação, controlar a concentração de metal livre ou melhorar a seletividade da titulação. Ao mesmo tempo, ele pode competir com o EDTA pelo metal, reduzindo a disponibilidade do metal livre e alterando o Kf efetivo. Por isso, seu efeito pode ajudar ou atrapalhar dependendo do sistema.",
    prioridade: 10,
  },
  {
    id: "complexometria_kf_efetivo_conceito",
    modulo: "complexometria",
    topico: "Kf efetivo",
    assunto: "kf_efetivo",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é Kf efetivo?",
      "O que significa constante efetiva?",
      "Definição de Kf efetivo",
    ],
    palavrasChave: [
      "kf efetivo",
      "constante efetiva",
      "constante de formação efetiva",
      "constante de formacao efetiva",
      "kf efetivo da complexometria",
    ],
    termosContexto: [
      "Kf efetivo",
      "Kf condicional",
      "α(Y⁴⁻)",
      "α(M livre)",
      "pH avaliado",
    ],
    termosEvitar: [
      "complexante auxiliar",
      "indicador",
      "ponto de equivalência",
      "curva",
    ],
    respostaCurta:
      "Kf efetivo representa a força de formação do complexo metal–EDTA nas condições consideradas pelo sistema.",
    respostaCompleta:
      "O Kf efetivo é uma constante ajustada às condições reais avaliadas na titulação. Ele pode considerar a fração ativa do EDTA, o pH e equilíbrios paralelos que alteram a disponibilidade do metal ou do ligante. Quanto maior seu valor, mais favorecida tende a ser a formação do complexo metal–EDTA.",
    prioridade: 10,
  },
  {
    id: "complexometria_indicador_decisao",
    modulo: "complexometria",
    topico: "Indicador",
    assunto: "indicador",
    intencao: "decisao",
    perguntasExemplo: [
      "Qual indicador devo usar?",
      "Qual é o melhor indicador?",
      "Qual indicador o sistema recomenda?",
    ],
    palavrasChave: [
      "qual indicador devo usar",
      "qual indicador usar",
      "melhor indicador",
      "indicador recomendado",
      "indicador mais compatível",
      "indicador mais compativel",
    ],
    termosContexto: [
      "indicador mais compatível",
      "compatibilidade do indicador",
      "pH avaliado",
      "metal principal",
    ],
    termosEvitar: ["indicador ácido-base", "indicador acido-base", "Kf efetivo"],
    respostaCurta:
      "Use como referência o indicador com maior compatibilidade calculada para o metal e o pH avaliados.",
    respostaCompleta:
      "Na complexometria, o indicador deve ser compatível com o metal principal, com o pH e com a região próxima ao ponto de equivalência. O indicador apontado pelo sistema representa a melhor opção entre os indicadores cadastrados e avaliados para aquela condição.",
    prioridade: 10,
  },
  {
    id: "complexometria_interferente_conceito",
    modulo: "complexometria",
    topico: "Interferente",
    assunto: "interferente",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é interferente?",
      "O que é metal interferente?",
      "O que atrapalha a titulação com EDTA?",
    ],
    palavrasChave: [
      "interferente",
      "metal interferente",
      "interferência",
      "interferencia",
      "competição pelo edta",
      "competicao pelo edta",
    ],
    termosContexto: [
      "interferentes avaliados",
      "risco de interferência",
      "metal principal",
      "Kf efetivo do interferente",
    ],
    termosEvitar: ["mascarante", "complexante auxiliar", "indicador"],
    respostaCurta:
      "Interferentes são espécies que podem competir com o metal principal pelo EDTA ou alterar o equilíbrio da titulação.",
    respostaCompleta:
      "Na complexometria, um interferente pode reagir com o EDTA, consumir parte do titulante, modificar a disponibilidade do metal principal ou afetar a detecção do ponto final. Seu impacto depende da afinidade pelo EDTA, da concentração e das condições do meio.",
    prioridade: 10,
  },
  {
    id: "geral_titulado_conceito",
    modulo: "geral",
    topico: "Titulado",
    assunto: "titulado",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulado?",
      "O que é solução titulada?",
      "Quem recebe o titulante?",
    ],
    palavrasChave: [
      "titulado",
      "solução titulada",
      "solucao titulada",
      "amostra titulada",
      "solução analisada",
      "solucao analisada",
      "quem recebe o titulante",
      "conteúdo do erlenmeyer",
      "conteudo do erlenmeyer",
    ],
    termosContexto: ["titulado", "amostra", "analito", "titulante"],
    termosEvitar: ["titulante", "indicador", "interferente"],
    respostaCurta:
      "Titulado é a solução que contém a espécie que será analisada na titulação.",
    respostaCompleta:
      "O titulado é a solução que recebe o titulante durante a titulação. Normalmente, ele contém o analito, ou seja, a espécie cuja quantidade ou concentração se deseja determinar. Em muitos procedimentos, o titulado fica no erlenmeyer ou no recipiente de reação.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_equivalencia_conceito",
    modulo: "geral",
    topico: "Ponto de equivalência",
    assunto: "ponto_equivalencia",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é ponto de equivalência?",
      "O que significa PE?",
      "O que é equivalência na titulação?",
    ],
    palavrasChave: [
      "ponto de equivalência",
      "ponto de equivalencia",
      "pe da titulação",
      "pe da titulacao",
      "equivalência",
      "equivalencia",
      "condição estequiométrica",
      "condicao estequiometrica",
    ],
    termosContexto: [
      "ponto de equivalência",
      "volume de equivalência",
      "estequiometria",
      "titulante",
      "analito",
    ],
    termosEvitar: [
      "ponto final",
      "indicador",
      "pH no PE",
      "complexometria",
      "ácido-base",
      "acido-base",
    ],
    respostaCurta:
      "Ponto de equivalência é a condição em que titulante e analito estão nas quantidades previstas pela estequiometria da reação.",
    respostaCompleta:
      "O ponto de equivalência é uma condição teórica da titulação. Ele ocorre quando a quantidade de titulante adicionada corresponde exatamente à quantidade necessária para reagir com o analito segundo a estequiometria da reação. Ele não depende, necessariamente, da mudança visual do indicador.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_final_conceito",
    modulo: "geral",
    topico: "Ponto final",
    assunto: "ponto_final",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é ponto final?",
      "O que é ponto final da titulação?",
      "Quando eu paro a titulação?",
    ],
    palavrasChave: [
      "ponto final",
      "ponto final da titulação",
      "ponto final da titulacao",
      "momento de parar",
      "fim da titulação",
      "fim da titulacao",
      "mudança observada",
      "mudanca observada",
      "sinal experimental",
    ],
    termosContexto: ["ponto final", "indicador", "mudança de cor", "sinal instrumental"],
    termosEvitar: ["ponto de equivalência", "ponto de equivalencia"],
    respostaCurta:
      "Ponto final é o sinal experimental usado para encerrar a titulação.",
    respostaCompleta:
      "O ponto final é o momento identificado experimentalmente para encerrar a titulação. Ele pode ser observado por mudança de cor, resposta instrumental ou outro sinal definido pelo método. O ideal é que o ponto final ocorra o mais próximo possível do ponto de equivalência.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_final_equivalencia_relacao",
    modulo: "geral",
    topico: "Ponto final e ponto de equivalência",
    assunto: "ponto_final_equivalencia",
    intencao: "comparacao",
    perguntasExemplo: [
      "Qual a diferença entre ponto final e ponto de equivalência?",
      "Ponto final é igual ao ponto de equivalência?",
      "Qual a diferença entre PE e ponto final?",
    ],
    palavrasChave: [
      "diferença entre ponto final e ponto de equivalência",
      "diferenca entre ponto final e ponto de equivalencia",
      "ponto final versus pe",
      "ponto final vs ponto de equivalência",
      "ponto final é igual ao pe",
      "ponto final e equivalência",
      "ponto final e equivalencia",
    ],
    termosContexto: ["ponto final", "ponto de equivalência", "indicador", "erro de titulação"],
    termosEvitar: ["volume de equivalência", "calcular PE"],
    respostaCurta:
      "O ponto de equivalência é teórico e estequiométrico; o ponto final é o sinal experimental observado.",
    respostaCompleta:
      "O ponto de equivalência corresponde à condição química ideal definida pela estequiometria da reação. Já o ponto final é o sinal observado na prática, como uma mudança de cor do indicador. Um bom método busca fazer o ponto final ocorrer o mais próximo possível do ponto de equivalência, reduzindo o erro de titulação.",
    prioridade: 10,
  },
  {
    id: "geral_curva_titulacao_conceito",
    modulo: "geral",
    topico: "Curva de titulação",
    assunto: "curva",
    intencao: "conceito",
    perguntasExemplo: [
      "O que representa a curva de titulação?",
      "O que é curva de titulação?",
      "Como interpretar uma curva de titulação?",
    ],
    palavrasChave: [
      "curva de titulação",
      "curva de titulacao",
      "gráfico da titulação",
      "grafico da titulacao",
      "propriedade versus volume",
      "volume de titulante",
      "curva volumétrica",
      "curva volumetrica",
    ],
    termosContexto: ["curva", "volume de titulante", "ponto de equivalência"],
    termosEvitar: [
      "curva ácido-base",
      "curva acido-base",
      "curva complexométrica",
      "curva complexometrica",
      "pM",
      "pH",
    ],
    respostaCurta:
      "A curva de titulação mostra como uma propriedade da solução varia conforme o titulante é adicionado.",
    respostaCompleta:
      "A curva de titulação representa a variação de uma propriedade do sistema em função do volume de titulante adicionado. Essa propriedade pode ser pH, pM, potencial ou outro sinal analítico, dependendo do tipo de titulação. A curva ajuda a visualizar regiões antes, próximas e depois do ponto de equivalência.",
    prioridade: 9,
  },
  {
    id: "geral_indicador_conceito",
    modulo: "geral",
    topico: "Indicador",
    assunto: "indicador",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é indicador?",
      "Para que serve um indicador?",
      "O que é indicador de titulação?",
    ],
    palavrasChave: [
      "indicador",
      "indicador químico",
      "indicador quimico",
      "indicador de titulação",
      "indicador de titulacao",
      "substância que muda de cor",
      "substancia que muda de cor",
      "função do indicador",
      "funcao do indicador",
    ],
    termosContexto: ["indicador", "ponto final", "mudança de cor"],
    termosEvitar: [
      "indicador complexométrico",
      "indicador complexometrico",
      "indicador ácido-base",
      "indicador acido-base",
      "qual indicador devo usar",
      "melhor indicador",
    ],
    respostaCurta:
      "Indicador é uma substância ou sistema que produz um sinal perceptível próximo ao ponto final da titulação.",
    respostaCompleta:
      "Um indicador é utilizado para sinalizar uma mudança importante durante a titulação, geralmente próxima ao ponto final. Em muitos casos, esse sinal é uma mudança de cor. A escolha do indicador depende do tipo de reação e da região em que se deseja detectar o final da titulação.",
    prioridade: 9,
  },
  {
    id: "geral_concentracao_molar_conceito",
    modulo: "geral",
    topico: "Concentração molar",
    assunto: "concentracao_molar",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é concentração molar?",
      "O que é molaridade?",
      "O que significa mol por litro?",
    ],
    palavrasChave: [
      "concentração molar",
      "concentracao molar",
      "molaridade",
      "mol por litro",
      "mol/l",
      "mol L",
      "quantidade de matéria por volume",
      "quantidade de materia por volume",
    ],
    termosContexto: ["concentração", "mol/L", "volume", "quantidade de matéria"],
    termosEvitar: [
      "concentração do EDTA",
      "concentracao do EDTA",
      "concentração do metal",
      "concentracao do metal",
      "metal livre",
    ],
    respostaCurta:
      "Concentração molar é a quantidade de matéria do soluto dividida pelo volume da solução em litros.",
    respostaCompleta:
      "A concentração molar, também chamada de molaridade, indica quantos mols de soluto existem em cada litro de solução. Ela é expressa por C = n/V, em que n é a quantidade de matéria em mol e V é o volume da solução em litros. Sua unidade usual é mol/L.",
    prioridade: 10,
  },
  {
    id: "geral_estequiometria_conceito",
    modulo: "geral",
    topico: "Estequiometria",
    assunto: "estequiometria",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é estequiometria?",
      "O que é relação molar?",
      "O que significa proporção entre reagentes?",
    ],
    palavrasChave: [
      "estequiometria",
      "relação molar",
      "relacao molar",
      "proporção entre reagentes",
      "proporcao entre reagentes",
      "coeficientes da equação",
      "coeficientes da equacao",
      "quantidade que reage",
    ],
    termosContexto: ["estequiometria", "equação balanceada", "relação molar"],
    termosEvitar: [
      "estequiometria metal edta",
      "proporção 1 para 1 edta",
      "calcular volume",
      "edta",
"metal edta",
"complexometria",
"complexométrica",
"complexometrica",
    ],
    respostaCurta:
      "Estequiometria é a relação quantitativa entre as espécies que participam de uma reação química.",
    respostaCompleta:
      "A estequiometria descreve a proporção em que reagentes e produtos participam de uma reação química. Em uma equação balanceada, os coeficientes indicam a relação entre os mols das espécies. Em titulações, essa relação permite converter o volume de titulante na quantidade de analito.",
    prioridade: 10,
  },
  {
    id: "geral_volume_equivalencia_conceito",
    modulo: "geral",
    topico: "Volume de equivalência",
    assunto: "volume_equivalencia",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é volume de equivalência?",
      "O que significa volume do PE?",
      "O que é volume necessário para atingir o PE?",
    ],
    palavrasChave: [
      "volume de equivalência",
      "volume de equivalencia",
      "volume do pe",
      "volume pe",
      "volume necessário",
      "volume necessario",
      "volume estequiométrico",
      "volume estequiometrico",
    ],
    termosContexto: ["volume de equivalência", "titulante", "ponto de equivalência"],
    termosEvitar: [
      "ponto final",
      "curva",
      "volume da amostra",
      "volume total",
    ],
    respostaCurta:
      "Volume de equivalência é o volume de titulante necessário para atingir o ponto de equivalência.",
    respostaCompleta:
      "O volume de equivalência corresponde ao volume de titulante necessário para reagir estequiometricamente com o analito presente na amostra. Ele depende da quantidade de analito, da concentração do titulante e da proporção da reação.",
    prioridade: 10,
  },
  {
    id: "geral_erro_titulacao_conceito",
    modulo: "geral",
    topico: "Erro de titulação",
    assunto: "erro_titulacao",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é erro de titulação?",
      "O que causa erro em uma titulação?",
      "Por que o resultado da titulação pode dar errado?",
    ],
    palavrasChave: [
      "erro de titulação",
      "erro de titulacao",
      "erro experimental",
      "erro analítico",
      "erro analitico",
      "resultado errado",
      "causas de erro",
    ],
    termosContexto: ["ponto final", "ponto de equivalência", "indicador", "volume"],
    termosEvitar: [
      "erro na complexometria",
      "erro ácido-base",
      "erro acido-base",
      "sistema não aceita valor",
      "campo inválido",
    ],
    respostaCurta:
      "Erro de titulação é a diferença entre o resultado obtido e o valor esperado ou verdadeiro.",
    respostaCompleta:
      "O erro de titulação pode surgir por diferença entre ponto final e ponto de equivalência, leitura incorreta do volume, preparo inadequado das soluções, escolha ruim do indicador, contaminação, perdas de amostra ou falhas no procedimento. Reduzir esses erros aumenta a confiabilidade da análise.",
    prioridade: 9,
  },
  {
    id: "geral_unidades_conceito",
    modulo: "geral",
    topico: "Unidades",
    assunto: "unidades",
    intencao: "conceito",
    perguntasExemplo: [
      "Quais unidades devo usar?",
      "A concentração é em mol por litro?",
      "O volume é em mL ou L?",
    ],
    palavrasChave: [
      "unidades",
      "quais unidades",
      "mol por litro",
      "mol/l",
      "ml",
      "l",
      "litro",
      "mililitro",
      "unidade de volume",
      "unidade de concentração",
      "unidade de concentracao",
    ],
    termosContexto: ["mol/L", "mL", "L", "concentração", "volume"],
    termosEvitar: [
      "misturei ml e l",
      "erro de conversão",
      "resultado mil vezes",
    ],
    respostaCurta:
      "As unidades devem seguir exatamente o que cada campo da interface solicita.",
    respostaCompleta:
      "Em geral, concentrações molares são expressas em mol/L, enquanto volumes podem ser informados em mL ou L, dependendo do campo. É importante seguir a unidade indicada pela interface, porque uma conversão incorreta pode alterar muito o resultado.",
    prioridade: 9,
  },
  {
    id: "geral_arredondamento_conceito",
    modulo: "geral",
    topico: "Arredondamento",
    assunto: "arredondamento",
    intencao: "conceito",
    perguntasExemplo: [
      "Por que os valores aparecem arredondados?",
      "Por que o valor exibido tem poucas casas decimais?",
      "O sistema usa mais casas decimais internamente?",
    ],
    palavrasChave: [
      "arredondamento",
      "valores arredondados",
      "casas decimais",
      "valor aproximado",
      "precisão exibida",
      "precisao exibida",
      "valor interno",
    ],
    termosContexto: ["resultado exibido", "casas decimais", "valor interno"],
    termosEvitar: [
      "erro grande",
      "falha no código",
      "falha no codigo",
      "unidade errada",
    ],
    respostaCurta:
      "O sistema pode exibir valores arredondados para facilitar a leitura dos resultados.",
    respostaCompleta:
      "O arredondamento reduz a quantidade de casas decimais mostradas na interface e torna os resultados mais legíveis. Em alguns casos, o cálculo interno pode usar mais precisão do que o valor exibido. Por isso, pequenas diferenças podem aparecer por arredondamento, sem indicar erro no cálculo.",
    prioridade: 8,
  },
  {
    id: "complexometria_metal_principal_conceito",
    modulo: "complexometria",
    topico: "Metal principal",
    assunto: "metal_principal",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é metal principal?",
      "O que significa metal principal?",
      "O que é o íon metálico analisado?",
    ],
    palavrasChave: [
      "metal principal",
      "íon metálico analisado",
      "ion metalico analisado",
      "analito metálico",
      "analito metalico",
      "metal titulado com edta",
      "cátion principal",
      "cation principal",
    ],
    termosContexto: [
      "metal principal",
      "complexo formado",
      "Kf efetivo",
      "indicador mais compatível",
    ],
    termosEvitar: [
      "metal interferente",
      "metal livre",
      "complexante auxiliar",
      "estado de oxidação",
    ],
    respostaCurta:
      "O metal principal é o íon metálico que se deseja determinar na titulação com EDTA.",
    respostaCompleta:
      "Na complexometria, o metal principal é o analito metálico selecionado para reagir com o EDTA. A identidade desse metal influencia o Kf, o Kf efetivo, a faixa de pH adequada, o indicador recomendado, a curva de titulação e o risco de interferências.",
    prioridade: 10,
  },
  {
    id: "complexometria_complexo_metal_edta_conceito",
    modulo: "complexometria",
    topico: "Complexo metal-EDTA",
    assunto: "complexo_metal_edta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é complexo metal-EDTA?",
      "O que é complexo MY?",
      "O que significa metal ligado ao EDTA?",
    ],
    palavrasChave: [
      "complexo metal edta",
      "complexo metal-edta",
      "complexo my",
      "espécie my",
      "especie my",
      "metal ligado ao edta",
      "produto da complexação",
      "produto da complexacao",
    ],
    termosContexto: [
      "complexo formado",
      "complexo metal–EDTA",
      "metal principal",
      "EDTA",
      "Kf efetivo",
    ],
    termosEvitar: [
      "complexo metal indicador",
      "complexante auxiliar",
      "interferente",
      "indicador",
    ],
    respostaCurta:
      "O complexo metal–EDTA é a espécie formada quando o metal principal se liga ao EDTA.",
    respostaCompleta:
      "O complexo metal–EDTA é o produto da reação entre o íon metálico e o EDTA. Muitas vezes ele é representado genericamente por MY. A estabilidade desse complexo depende da constante de formação e das condições químicas do meio, como pH e reações paralelas.",
    prioridade: 10,
  },
  {
    id: "complexometria_kf_conceito",
    modulo: "complexometria",
    topico: "Kf",
    assunto: "kf",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é Kf?",
      "O que é constante de formação?",
      "O que significa estabilidade do complexo?",
    ],
    palavrasChave: [
      "kf",
      "constante de formação",
      "constante de formacao",
      "constante global de formação",
      "constante global de formacao",
      "estabilidade do complexo",
      "beta de formação",
      "beta de formacao",
    ],
    termosContexto: [
      "Kf",
      "complexo metal–EDTA",
      "Kf condicional",
      "Kf efetivo",
    ],
    termosEvitar: [
      "Kf efetivo",
      "Kf condicional",
      "alfa do EDTA",
      "indicador",
      "valor calculado",
    ],
    respostaCurta:
      "Kf é a constante de formação que expressa a estabilidade do complexo metal–EDTA.",
    respostaCompleta:
      "O Kf representa o equilíbrio de formação do complexo entre o metal e o EDTA em uma condição de referência. Quanto maior o Kf, mais favorecida é a formação do complexo. Porém, para interpretar uma titulação real, muitas vezes é necessário considerar constantes condicionais ou efetivas.",
    prioridade: 10,
  },
  {
    id: "complexometria_kf_condicional_conceito",
    modulo: "complexometria",
    topico: "Kf condicional",
    assunto: "kf_condicional",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é Kf condicional?",
      "O que significa constante condicional?",
      "O que é Kf ajustado pelo alfa do EDTA?",
    ],
    palavrasChave: [
      "kf condicional",
      "constante condicional",
      "constante aparente",
      "kf ajustado pelo alfa",
      "kf ajustado pelo ph",
      "disponibilidade do edta",
    ],
    termosContexto: [
      "Kf condicional",
      "Kf",
      "α(Y⁴⁻)",
      "pH avaliado",
    ],
    termosEvitar: [
      "Kf efetivo",
      "alfa do metal",
      "complexante auxiliar",
      "status quantitativo",
    ],
    respostaCurta:
      "Kf condicional é a constante de formação ajustada à disponibilidade do EDTA nas condições do meio.",
    respostaCompleta:
      "O Kf condicional considera que apenas uma fração do EDTA total está disponível na forma de referência para complexar o metal. Como essa fração depende principalmente do pH, o Kf condicional representa melhor a formação aparente do complexo naquele meio.",
    prioridade: 10,
  },
  {
    id: "complexometria_alfa_edta_conceito",
    modulo: "complexometria",
    topico: "α do EDTA",
    assunto: "alfa_edta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é alfa do EDTA?",
      "O que é α(Y⁴⁻)?",
      "O que significa fração ativa do EDTA?",
    ],
    palavrasChave: [
      "alfa do edta",
      "α do edta",
      "α(y4-)",
      "α(Y⁴⁻)",
      "fração ativa do edta",
      "fracao ativa do edta",
      "forma ativa y4",
      "disponibilidade do edta",
    ],
    termosContexto: [
      "α(Y⁴⁻)",
      "pH avaliado",
      "Kf condicional",
      "Kf efetivo",
    ],
    termosEvitar: [
      "alfa do metal",
      "metal livre",
      "complexante auxiliar",
      "indicador",
    ],
    respostaCurta:
      "α(Y⁴⁻) representa a fração do EDTA presente na forma ativa Y⁴⁻ nas condições avaliadas.",
    respostaCompleta:
      "O α(Y⁴⁻) indica qual fração do EDTA total está na forma Y⁴⁻. Esse valor depende do pH: em meio mais ácido, o EDTA fica mais protonado e a fração Y⁴⁻ diminui; em pH mais alto, essa fração tende a aumentar. Isso influencia diretamente o Kf condicional.",
    prioridade: 10,
  },
  {
    id: "complexometria_alfa_metal_conceito",
    modulo: "complexometria",
    topico: "α do metal",
    assunto: "alfa_metal",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é alfa do metal?",
      "O que é α(M livre)?",
      "O que significa fração disponível do metal?",
    ],
    palavrasChave: [
      "alfa do metal",
      "α do metal",
      "α(M livre)",
      "alfa m livre",
      "fração disponível do metal",
      "fracao disponivel do metal",
      "metal disponível",
      "metal disponivel",
    ],
    termosContexto: [
      "α(M livre)",
      "denominador β",
      "complexante auxiliar",
      "Kf efetivo",
    ],
    termosEvitar: [
      "alfa do EDTA",
      "α(Y⁴⁻)",
      "percentual complexado",
      "metal principal",
    ],
    respostaCurta:
      "α(M livre) representa a fração do metal total disponível na forma livre considerada pelo modelo.",
    respostaCompleta:
      "O α(M livre) considera a distribuição do metal entre a forma livre e espécies formadas em equilíbrios paralelos, como complexos com ligantes auxiliares. Quanto menor esse valor, menor a fração do metal disponível para reagir diretamente com o EDTA.",
    prioridade: 9,
  },
  {
    id: "complexometria_denominador_beta_conceito",
    modulo: "complexometria",
    topico: "Denominador beta",
    assunto: "denominador_beta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é denominador beta?",
      "O que significa denominador β?",
      "O que é beta nas reações paralelas?",
    ],
    palavrasChave: [
      "denominador beta",
      "denominador β",
      "soma beta",
      "reações paralelas",
      "reacoes paralelas",
      "correção por complexos auxiliares",
      "correcao por complexos auxiliares",
    ],
    termosContexto: [
      "denominador β",
      "α(M livre)",
      "complexante auxiliar",
      "Kf efetivo",
    ],
    termosEvitar: [
      "beta como Kf",
      "constante global de formação",
      "indicador",
      "ponto de equivalência",
    ],
    respostaCurta:
      "O denominador beta reúne contribuições de equilíbrios paralelos que alteram a fração livre de uma espécie.",
    respostaCompleta:
      "Em modelos de complexação, o denominador beta pode representar a soma das espécies formadas em equilíbrios paralelos. Ele ajuda a calcular quanto do metal permanece na forma livre disponível para a reação principal com EDTA. Quando esse denominador aumenta, a fração livre tende a diminuir.",
    prioridade: 8,
  },
  {
    id: "complexometria_estequiometria_metal_edta_conceito",
    modulo: "complexometria",
    topico: "Estequiometria metal-EDTA",
    assunto: "estequiometria_metal_edta",
    intencao: "conceito",
    perguntasExemplo: [
      "Qual é a estequiometria da titulação com EDTA?",
      "A proporção metal EDTA é 1 para 1?",
      "Quantos mols de EDTA reagem com o metal?",
    ],
    palavrasChave: [
      "estequiometria metal edta",
      "proporção 1 para 1 edta",
      "proporcao 1 para 1 edta",
      "relação molar metal edta",
      "relacao molar metal edta",
      "1:1 metal edta",
      "mol de edta por mol de metal",
    ],
    termosContexto: [
      "estequiometria metal–EDTA",
      "metal principal",
      "EDTA",
      "volume de equivalência",
    ],
    termosEvitar: [
      "estequiometria geral",
      "calcular valor numérico",
      "indicador",
      "complexante auxiliar",
    ],
    respostaCurta:
      "Na maioria das titulações complexométricas com EDTA, a proporção molar metal:EDTA é 1:1.",
    respostaCompleta:
      "Em condições clássicas, um mol de EDTA forma complexo com um mol do íon metálico, independentemente da carga do metal. Essa relação 1:1 é usada nos cálculos da quantidade de metal e do volume de equivalência.",
    prioridade: 10,
  },
  {
    id: "complexometria_ponto_equivalencia_conceito",
    modulo: "complexometria",
    topico: "Ponto de equivalência",
    assunto: "ponto_equivalencia_complexometria",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é ponto de equivalência na complexometria?",
      "O que é PE na titulação com EDTA?",
      "Quando ocorre a equivalência metal EDTA?",
    ],
    palavrasChave: [
      "ponto de equivalência da complexometria",
      "ponto de equivalencia da complexometria",
      "pe metal edta",
      "equivalência metal edta",
      "equivalencia metal edta",
      "ponto estequiométrico do edta",
      "ponto estequiometrico do edta",
    ],
    termosContexto: [
      "volume de equivalência",
      "metal principal",
      "EDTA",
      "estequiometria metal–EDTA",
    ],
    termosEvitar: [
      "ponto final",
      "ponto de equivalência geral",
      "pH no PE ácido-base",
      "neutralização",
    ],
    respostaCurta:
      "Na complexometria, o ponto de equivalência ocorre quando EDTA e metal principal estão na proporção estequiométrica da reação.",
    respostaCompleta:
      "Na titulação complexométrica, o ponto de equivalência ocorre quando a quantidade de EDTA adicionada é estequiometricamente equivalente à quantidade total do metal principal. Esse ponto é definido pela relação química da reação, e não pela mudança visual do indicador.",
    prioridade: 10,
  },
  {
    id: "complexometria_volume_equivalencia_conceito",
    modulo: "complexometria",
    topico: "Volume de equivalência com EDTA",
    assunto: "volume_equivalencia_edta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que significa volume de equivalência com EDTA?",
      "O que é volume de EDTA no PE?",
      "O que é volume necessário de EDTA?",
    ],
    palavrasChave: [
      "volume de equivalência do edta",
      "volume de equivalencia do edta",
      "volume necessário de edta",
      "volume necessario de edta",
      "volume pe complexométrico",
      "volume pe complexometrico",
      "volume estequiométrico de edta",
      "volume estequiometrico de edta",
    ],
    termosContexto: [
      "volume de equivalência",
      "concentração do EDTA",
      "concentração do metal",
      "volume da amostra",
      "estequiometria metal–EDTA",
    ],
    termosEvitar: [
      "volume total",
      "volume da amostra",
      "ponto final",
      "curva",
    ],
    respostaCurta:
      "É o volume de EDTA necessário para atingir a proporção estequiométrica com o metal principal.",
    respostaCompleta:
      "Na complexometria, o volume de equivalência corresponde ao volume de EDTA necessário para que os mols adicionados sejam equivalentes aos mols do metal principal. Ele depende da concentração do EDTA, da quantidade de metal na amostra e da estequiometria da reação.",
    prioridade: 10,
  },
  {
    id: "complexometria_pm_conceito",
    modulo: "complexometria",
    topico: "pM",
    assunto: "pm",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é pM?",
      "O que significa pM?",
      "O que é menos log do metal livre?",
    ],
    palavrasChave: [
      "pm",
      "pM",
      "o que é pm",
      "definição de pm",
      "definicao de pm",
      "menos log do metal livre",
      "escala de metal livre",
    ],
    termosContexto: [
      "pM",
      "[M] livre",
      "metal livre",
      "curva complexométrica",
    ],
    termosEvitar: [
      "pH",
      "ácido-base",
      "acido-base",
      "indicador",
    ],
    respostaCurta:
      "pM é o negativo do logaritmo da concentração molar do metal livre.",
    respostaCompleta:
      "O pM é definido por pM = −log[M], em que [M] representa a concentração molar do metal livre. Assim, valores maiores de pM indicam menores concentrações de metal livre.",
    prioridade: 10,
  },
  {
    id: "complexometria_metal_livre_conceito",
    modulo: "complexometria",
    topico: "Metal livre",
    assunto: "metal_livre",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é metal livre?",
      "O que significa [M] livre?",
      "O que é concentração de metal livre?",
    ],
    palavrasChave: [
      "metal livre",
      "[m] livre",
      "concentração de metal livre",
      "concentracao de metal livre",
      "íon metálico não complexado",
      "ion metalico nao complexado",
      "metal não complexado",
      "metal nao complexado",
    ],
    termosContexto: [
      "[M] livre",
      "pM",
      "complexo metal–EDTA",
      "percentual complexado",
    ],
    termosEvitar: [
      "metal principal",
      "concentração inicial",
      "alfa do metal",
      "interferente",
    ],
    respostaCurta:
      "Metal livre é a fração do metal que não está ligada ao EDTA nas espécies consideradas como complexadas.",
    respostaCompleta:
      "Na interpretação da titulação, [M] livre representa a concentração da espécie metálica disponível na forma definida pelo modelo. Essa concentração tende a diminuir conforme o EDTA é adicionado e o complexo metal–EDTA é formado.",
    prioridade: 9,
  },
  {
    id: "complexometria_percentual_complexado_conceito",
    modulo: "complexometria",
    topico: "Percentual complexado",
    assunto: "percentual_complexado",
    intencao: "conceito",
    perguntasExemplo: [
      "O que significa percentual complexado?",
      "O que é porcentagem do metal complexado?",
      "O que significa % complexado?",
    ],
    palavrasChave: [
      "percentual complexado",
      "porcentagem complexada",
      "porcentagem do metal complexado",
      "% complexado",
      "fração complexada",
      "fracao complexada",
      "quanto do metal ligou ao edta",
    ],
    termosContexto: [
      "% complexado",
      "[MY]",
      "[M] livre",
      "metal principal",
      "complexo metal–EDTA",
    ],
    termosEvitar: [
      "rendimento de síntese",
      "rendimento de sintese",
      "pureza",
      "indicador",
    ],
    respostaCurta:
      "O percentual complexado indica qual fração do metal principal está ligada ao EDTA.",
    respostaCompleta:
      "O percentual complexado relaciona a quantidade de metal presente como complexo metal–EDTA com a quantidade total considerada. Valores altos indicam predominância do complexo; valores baixos indicam maior presença de metal não complexado.",
    prioridade: 9,
  },
  {
    id: "complexometria_sistema_quantitativo_interpretacao",
    modulo: "complexometria",
    topico: "Sistema quantitativo",
    assunto: "sistema_quantitativo",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Esse sistema é quantitativo?",
      "A titulação é quantitativa?",
      "Esse resultado é bom para titular?",
    ],
    palavrasChave: [
      "sistema quantitativo",
      "titulação quantitativa",
      "titulacao quantitativa",
      "resultado quantitativo",
      "é bom para titular",
      "e bom para titular",
      "dá para titular",
      "da para titular",
      "sistema bom",
    ],
    termosContexto: [
      "Status da titulação",
      "Kf efetivo",
      "pH avaliado",
      "metal principal",
    ],
    termosEvitar: [
      "banana",
      "fora do sistema",
      "indicador apenas",
    ],
    respostaCurta:
      "Um sistema tende a ser quantitativo quando a formação do complexo metal–EDTA é suficientemente favorecida nas condições avaliadas.",
    respostaCompleta:
      "Na complexometria, um sistema é considerado mais adequado para titulação quantitativa quando o complexo metal–EDTA se forma de maneira intensa e bem definida nas condições escolhidas. O Kf efetivo, o pH, a disponibilidade do EDTA e possíveis equilíbrios paralelos influenciam essa avaliação. Quanto maior o favorecimento da complexação, mais confiável tende a ser a titulação.",
    prioridade: 10,
  },
  {
    id: "complexometria_kf_efetivo_baixo_interpretacao",
    modulo: "complexometria",
    topico: "Kf efetivo baixo",
    assunto: "kf_efetivo_baixo",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Por que o Kf efetivo ficou baixo?",
      "Por que a constante efetiva está baixa?",
      "Por que o sistema não ficou quantitativo?",
    ],
    palavrasChave: [
      "kf efetivo baixo",
      "kf efetivo ficou baixo",
      "constante efetiva baixa",
      "sistema não quantitativo",
      "sistema nao quantitativo",
      "formação fraca do complexo",
      "formacao fraca do complexo",
      "complexo pouco favorecido",
    ],
    termosContexto: [
      "Kf efetivo",
      "Kf condicional",
      "α(Y⁴⁻)",
      "α(M livre)",
      "pH avaliado",
      "complexante auxiliar",
    ],
    termosEvitar: [
      "Kf conceito",
      "indicador",
      "volume de equivalência",
    ],
    respostaCurta:
      "O Kf efetivo pode ficar baixo quando o EDTA ou o metal estão pouco disponíveis para formar o complexo.",
    respostaCompleta:
      "O Kf efetivo pode diminuir quando o pH reduz a fração ativa do EDTA, quando o metal está envolvido em reações paralelas, quando há complexante auxiliar competindo com o EDTA ou quando as condições do meio não favorecem a formação do complexo metal–EDTA. Nesses casos, a titulação pode ficar menos quantitativa ou apresentar ponto final menos definido.",
    prioridade: 10,
  },
  {
    id: "complexometria_ph_adequado_interpretacao",
    modulo: "complexometria",
    topico: "pH adequado",
    assunto: "ph_adequado",
    intencao: "interpretacao",
    perguntasExemplo: [
      "O pH está adequado?",
      "Esse pH é bom para a titulação?",
      "Por que o pH importa na complexometria?",
    ],
    palavrasChave: [
      "ph adequado",
      "pH adequado",
      "ph está adequado",
      "ph esta adequado",
      "pH está adequado",
      "esse ph é bom",
      "esse ph e bom",
      "pH bom",
      "importância do ph",
      "importancia do ph",
      "por que o ph importa",
    ],
    termosContexto: [
      "pH avaliado",
      "α(Y⁴⁻)",
      "Kf condicional",
      "Kf efetivo",
      "faixa de pH",
    ],
    termosEvitar: [
      "pH ácido-base",
      "neutralização",
      "tampão apenas",
    ],
    respostaCurta:
      "O pH é adequado quando favorece a disponibilidade do EDTA e mantém o metal em condição apropriada para complexar.",
    respostaCompleta:
      "Na complexometria com EDTA, o pH é fundamental porque altera a fração ativa do EDTA e pode influenciar a forma química do metal. Em pH muito baixo, o EDTA fica mais protonado e menos disponível como Y⁴⁻. Em pH muito alto, alguns metais podem sofrer reações paralelas, como hidrólise ou precipitação. Por isso, cada metal tende a ter uma faixa de pH mais adequada.",
    prioridade: 10,
  },
  {
    id: "complexometria_indicador_confiavel_interpretacao",
    modulo: "complexometria",
    topico: "Indicador confiável",
    assunto: "indicador_confiavel",
    intencao: "interpretacao",
    perguntasExemplo: [
      "O indicador recomendado é confiável?",
      "Esse indicador é bom?",
      "Posso confiar no indicador sugerido?",
    ],
    palavrasChave: [
      "indicador confiável",
      "indicador confiavel",
      "indicador recomendado é confiável",
      "indicador recomendado e confiavel",
      "esse indicador é bom",
      "esse indicador e bom",
      "posso confiar no indicador",
      "indicador sugerido",
    ],
    termosContexto: [
      "Indicador mais compatível",
      "compatibilidade",
      "metal principal",
      "pH avaliado",
    ],
    termosEvitar: [
      "indicador conceito geral",
      "indicador ácido-base",
      "indicador acido-base",
    ],
    respostaCurta:
      "O indicador é mais confiável quando é compatível com o metal e com o pH avaliados.",
    respostaCompleta:
      "Na titulação complexométrica, o indicador precisa formar um complexo com o metal que permita observar a mudança próxima ao ponto final, mas sem competir excessivamente com o EDTA. A confiabilidade aumenta quando o indicador é compatível com o metal principal, atua na faixa de pH avaliada e apresenta boa resposta na região próxima ao ponto de equivalência.",
    prioridade: 10,
  },
  {
    id: "complexometria_interferente_atrapalha_interpretacao",
    modulo: "complexometria",
    topico: "Interferente",
    assunto: "interferente_atrapalha",
    intencao: "interpretacao",
    perguntasExemplo: [
      "O interferente atrapalha?",
      "Esse interferente interfere na titulação?",
      "Por que aparece risco de interferência?",
    ],
    palavrasChave: [
      "interferente atrapalha",
      "interferente interfere",
      "risco de interferência",
      "risco de interferencia",
      "por que aparece risco",
      "metal interferente atrapalha",
      "competição com edta",
      "competicao com edta",
    ],
    termosContexto: [
      "Interferentes avaliados",
      "risco",
      "metal principal",
      "Kf efetivo",
      "EDTA",
    ],
    termosEvitar: [
      "mascarante conceito",
      "complexante auxiliar",
      "indicador",
    ],
    respostaCurta:
      "Um interferente atrapalha quando compete com o metal principal pelo EDTA ou altera a detecção do ponto final.",
    respostaCompleta:
      "Na complexometria, um interferente pode atrapalhar ao consumir EDTA, formar complexos estáveis, deslocar equilíbrios ou dificultar a visualização do ponto final. O risco depende da concentração do interferente, da afinidade dele pelo EDTA, do pH e da diferença de comportamento em relação ao metal principal.",
    prioridade: 10,
  },
  {
    id: "complexometria_titulacao_parcial_interpretacao",
    modulo: "complexometria",
    topico: "Titulação parcial",
    assunto: "titulacao_parcial",
    intencao: "interpretacao",
    perguntasExemplo: [
      "O que significa titulação parcial?",
      "Por que a titulação ficou parcial?",
      "O que é sistema parcialmente quantitativo?",
    ],
    palavrasChave: [
      "titulação parcial",
      "titulacao parcial",
      "sistema parcialmente quantitativo",
      "parcialmente quantitativo",
      "resultado parcial",
      "titulação não totalmente quantitativa",
      "titulacao nao totalmente quantitativa",
    ],
    termosContexto: [
      "Status da titulação",
      "Kf efetivo",
      "formação parcial",
      "complexo metal–EDTA",
    ],
    termosEvitar: [
      "ponto final",
      "volume parcial",
      "amostra parcial",
    ],
    respostaCurta:
      "Titulação parcial indica que a formação do complexo ocorre, mas pode não ser suficientemente favorecida para uma titulação plenamente quantitativa.",
    respostaCompleta:
      "Uma titulação parcial sugere que o sistema apresenta formação do complexo metal–EDTA, mas as condições avaliadas não garantem uma reação tão completa quanto o ideal. Isso pode ocorrer por Kf efetivo intermediário, pH inadequado, baixa disponibilidade do EDTA ou competição por reações paralelas.",
    prioridade: 10,
  },
  {
    id: "complexometria_titulacao_ruim_interpretacao",
    modulo: "complexometria",
    topico: "Titulação ruim",
    assunto: "titulacao_ruim",
    intencao: "interpretacao",
    perguntasExemplo: [
      "O que significa titulação ruim?",
      "Por que a titulação é ruim?",
      "O sistema não serve para titular?",
    ],
    palavrasChave: [
      "titulação ruim",
      "titulacao ruim",
      "sistema ruim",
      "não serve para titular",
      "nao serve para titular",
      "titulação inviável",
      "titulacao inviavel",
      "complexação insuficiente",
      "complexacao insuficiente",
    ],
    termosContexto: [
      "Status da titulação",
      "Kf efetivo",
      "mensagem do sistema",
      "complexo metal–EDTA",
    ],
    termosEvitar: [
      "erro de interface",
      "erro de código",
      "erro de codigo",
    ],
    respostaCurta:
      "Titulação ruim indica que as condições avaliadas não favorecem suficientemente a formação do complexo metal–EDTA.",
    respostaCompleta:
      "Quando o sistema é classificado como ruim, isso sugere que a reação entre metal e EDTA pode não ser suficientemente completa ou definida para uma titulação confiável. As causas mais comuns são Kf efetivo baixo, pH inadequado, baixa fração ativa do EDTA, reações paralelas ou interferências relevantes.",
    prioridade: 10,
  },
  {
    id: "complexometria_mascarante_interpretacao",
    modulo: "complexometria",
    topico: "Mascarante",
    assunto: "mascarante",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Para que serve o mascarante?",
      "O que é mascarante na complexometria?",
      "Como o mascarante ajuda na titulação?",
    ],
    palavrasChave: [
      "mascarante",
      "agente mascarante",
      "mascaramento",
      "mascarar interferente",
      "para que serve o mascarante",
      "como o mascarante ajuda",
      "bloquear interferente",
    ],
    termosContexto: [
      "mascarante",
      "interferente",
      "seletividade",
      "EDTA",
    ],
    termosEvitar: [
      "complexante auxiliar",
      "indicador",
      "titulante",
    ],
    respostaCurta:
      "Mascarante é uma espécie usada para reduzir a interferência de outros íons na titulação.",
    respostaCompleta:
      "Na complexometria, um mascarante é utilizado para diminuir ou bloquear a participação de espécies interferentes. Ele pode se ligar seletivamente a um interferente, impedindo que esse íon reaja com o EDTA ou atrapalhe o ponto final. Assim, o mascarante aumenta a seletividade da titulação.",
    prioridade: 10,
  },
  {
    id: "complexometria_curva_interpretacao",
    modulo: "complexometria",
    topico: "Curva complexométrica",
    assunto: "curva_complexometrica",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Como interpretar a curva complexométrica?",
      "O que a curva com EDTA mostra?",
      "O que representa a curva de pM?",
    ],
    palavrasChave: [
      "curva complexométrica",
      "curva complexometrica",
      "curva com edta",
      "curva de pm",
      "curva pM",
      "interpretar curva complexométrica",
      "interpretar curva complexometrica",
      "gráfico pM",
      "grafico pm",
    ],
    termosContexto: [
      "curva complexométrica",
      "pM",
      "volume de equivalência",
      "metal livre",
    ],
    termosEvitar: [
      "curva ácido-base",
      "curva acido-base",
      "pH",
    ],
    respostaCurta:
      "A curva complexométrica mostra como o metal livre varia conforme o EDTA é adicionado.",
    respostaCompleta:
      "Na titulação com EDTA, a curva geralmente acompanha uma grandeza relacionada ao metal livre, como pM. Antes do ponto de equivalência, ainda há metal livre em excesso. Próximo ao ponto de equivalência, ocorre mudança mais intensa na concentração de metal livre. Depois do ponto de equivalência, o EDTA passa a ficar em excesso.",
    prioridade: 9,
  },
];