import type { ItemConhecimento } from "./tipos";

export const baseConhecimento: ItemConhecimento[] = [
  {
    id: "geral_titulacao_conceito",
    modulo: "geral",
    topico: "Titulação",
    assunto: "titulacao",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulação?",
      "O que é uma titulção?",
      "O que significa análise volumétrica?",
    ],
    palavrasChave: [
      "titulação",
      "titulacao",
      "titulção",
      "titulcao",
      "análise volumétrica",
      "analise volumetrica",
      "método volumétrico",
      "metodo volumetrico",
    ],
    termosContexto: ["titulante", "titulado", "ponto de equivalência"],
    termosEvitar: [
      "curva ácido-base",
      "curva complexométrica",
      "indicador",
      "interferente",
    ],
    respostaCurta:
      "Titulação é um método analítico usado para determinar a quantidade ou concentração de uma substância por meio de uma reação química.",
    respostaCompleta:
      "Titulação é um método analítico em que uma solução de concentração conhecida é adicionada gradualmente à amostra até atingir uma condição relacionada à estequiometria da reação. O volume gasto permite determinar a quantidade ou concentração do analito.",
    prioridade: 10,
  },
  {
    id: "geral_titulante_conceito",
    modulo: "geral",
    topico: "Titulante",
    assunto: "titulante",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulante?",
      "Quem fica na bureta?",
      "O que é solução titulante?",
    ],
    palavrasChave: [
      "titulante",
      "solução titulante",
      "solucao titulante",
      "reagente de concentração conhecida",
      "quem fica na bureta",
    ],
    termosContexto: ["titulante", "volume adicionado"],
    termosEvitar: ["titulado", "analito", "edta especificamente"],
    respostaCurta:
      "Titulante é a solução adicionada durante a titulação, geralmente com concentração conhecida ou padronizada.",
    respostaCompleta:
      "O titulante é a solução adicionada progressivamente à amostra durante a titulação. Ele reage com o analito segundo uma relação estequiométrica conhecida, e o volume utilizado é usado para calcular a quantidade da espécie analisada.",
    prioridade: 10,
  },
  {
    id: "geral_analito_conceito",
    modulo: "geral",
    topico: "Analito",
    assunto: "analito",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é analito?",
      "O que está sendo medido?",
      "Qual é a espécie analisada?",
    ],
    palavrasChave: [
      "analito",
      "espécie analisada",
      "especie analisada",
      "substância analisada",
      "substancia analisada",
      "componente de interesse",
    ],
    termosContexto: ["analito", "amostra"],
    termosEvitar: ["titulante", "indicador", "interferente"],
    respostaCurta:
      "Analito é a espécie química cuja quantidade ou concentração se deseja determinar.",
    respostaCompleta:
      "O analito é o componente de interesse da amostra. Em uma titulação, sua quantidade é determinada a partir da reação com o titulante e da relação estequiométrica entre as espécies envolvidas.",
    prioridade: 10,
  },
  {
    id: "complexometria_edta_conceito",
    modulo: "complexometria",
    topico: "EDTA",
    assunto: "edta",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é EDTA?",
      "O que é titulante EDTA?",
      "EDTA é o quê na complexometria?",
    ],
    palavrasChave: [
      "edta",
      "titulante edta",
      "agente quelante edta",
      "ligante edta",
      "ácido etilenodiaminotetracético",
      "acido etilenodiaminotetracetico",
    ],
    termosContexto: ["EDTA", "complexo metal–EDTA", "metal principal"],
    termosEvitar: [
      "complexante auxiliar",
      "ligante auxiliar",
      "amônia",
      "amonia",
      "mascarante",
      "indicador",
      "interferente",
    ],
    respostaCurta:
      "O EDTA é um ligante polidentado usado para formar complexos estáveis com íons metálicos.",
    respostaCompleta:
      "Em titulações complexométricas, o EDTA geralmente atua como titulante. Ele possui vários átomos doadores e forma complexos estáveis com muitos íons metálicos, normalmente em proporção molar 1:1.",
    prioridade: 10,
  },
  {
    id: "complexometria_ligante_auxiliar_conceito",
    modulo: "complexometria",
    topico: "Ligante auxiliar",
    assunto: "ligante_auxiliar",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é complexante auxiliar?",
      "O que seria um ligante auxiliar?",
      "O que é complexante secundário?",
    ],
    palavrasChave: [
      "complexante auxiliar",
      "ligante auxiliar",
      "agente auxiliar",
      "complexante secundário",
      "complexante secundario",
      "complexante de apoio",
      "amônia",
      "amonia",
      "nh3",
    ],
    termosContexto: [
      "complexante auxiliar",
      "ligante auxiliar",
      "α(M livre)",
      "denominador β",
      "Kf efetivo",
    ],
    termosEvitar: [
      "EDTA como titulante principal",
      "indicador",
      "mascarante",
      "interferente metálico",
    ],
    respostaCurta:
      "Complexante auxiliar é uma espécie que também se liga ao metal e altera sua disponibilidade para reagir com o EDTA.",
    respostaCompleta:
      "Um complexante auxiliar, também chamado de ligante auxiliar, é uma espécie que pode se ligar ao metal principal além do EDTA. Ele pode ajudar a manter o metal dissolvido, evitar precipitação ou controlar a concentração de metal livre. Porém, como também compete com o EDTA, pode alterar o Kf efetivo e precisa ser considerado no equilíbrio do sistema.",
    prioridade: 10,
  },
  {
    id: "complexometria_ligante_auxiliar_interpretacao",
    modulo: "complexometria",
    topico: "Ligante auxiliar",
    assunto: "ligante_auxiliar",
    intencao: "interpretacao",
    perguntasExemplo: [
      "Por que se usa complexante auxiliar?",
      "Para que serve o ligante auxiliar?",
      "Por que usar amônia na complexometria?",
    ],
    palavrasChave: [
      "por que usa complexante auxiliar",
      "pq usa complexante auxiliar",
      "para que serve complexante auxiliar",
      "função do complexante auxiliar",
      "funcao do complexante auxiliar",
      "por que usar ligante auxiliar",
      "complexante auxiliar atrapalha",
    ],
    termosContexto: [
      "complexante auxiliar",
      "ligante auxiliar",
      "Kf efetivo",
      "denominador β",
      "α(M livre)",
      "precipitação",
    ],
    termosEvitar: [
      "Kf efetivo isolado",
      "EDTA como titulante",
      "indicador",
      "interferente metálico",
    ],
    respostaCurta:
      "Usa-se um complexante auxiliar para controlar a disponibilidade do metal e melhorar as condições da titulação.",
    respostaCompleta:
      "Um complexante auxiliar pode ser usado para manter o metal em solução, evitar precipitação, controlar a concentração de metal livre ou melhorar a seletividade da titulação. Ao mesmo tempo, ele pode competir com o EDTA pelo metal, reduzindo a disponibilidade do metal livre e alterando o Kf efetivo. Por isso, seu efeito pode ajudar ou atrapalhar dependendo do sistema.",
    prioridade: 10,
  },
  {
    id: "complexometria_kf_efetivo_conceito",
    modulo: "complexometria",
    topico: "Kf efetivo",
    assunto: "kf_efetivo",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é Kf efetivo?",
      "O que significa constante efetiva?",
      "Definição de Kf efetivo",
    ],
    palavrasChave: [
      "kf efetivo",
      "constante efetiva",
      "constante de formação efetiva",
      "constante de formacao efetiva",
      "kf efetivo da complexometria",
    ],
    termosContexto: [
      "Kf efetivo",
      "Kf condicional",
      "α(Y⁴⁻)",
      "α(M livre)",
      "pH avaliado",
    ],
    termosEvitar: [
      "complexante auxiliar",
      "indicador",
      "ponto de equivalência",
      "curva",
    ],
    respostaCurta:
      "Kf efetivo representa a força de formação do complexo metal–EDTA nas condições consideradas pelo sistema.",
    respostaCompleta:
      "O Kf efetivo é uma constante ajustada às condições reais avaliadas na titulação. Ele pode considerar a fração ativa do EDTA, o pH e equilíbrios paralelos que alteram a disponibilidade do metal ou do ligante. Quanto maior seu valor, mais favorecida tende a ser a formação do complexo metal–EDTA.",
    prioridade: 10,
  },
  {
    id: "complexometria_indicador_decisao",
    modulo: "complexometria",
    topico: "Indicador",
    assunto: "indicador",
    intencao: "decisao",
    perguntasExemplo: [
      "Qual indicador devo usar?",
      "Qual é o melhor indicador?",
      "Qual indicador o sistema recomenda?",
    ],
    palavrasChave: [
      "qual indicador devo usar",
      "qual indicador usar",
      "melhor indicador",
      "indicador recomendado",
      "indicador mais compatível",
      "indicador mais compativel",
    ],
    termosContexto: [
      "indicador mais compatível",
      "compatibilidade do indicador",
      "pH avaliado",
      "metal principal",
    ],
    termosEvitar: ["indicador ácido-base", "indicador acido-base", "Kf efetivo"],
    respostaCurta:
      "Use como referência o indicador com maior compatibilidade calculada para o metal e o pH avaliados.",
    respostaCompleta:
      "Na complexometria, o indicador deve ser compatível com o metal principal, com o pH e com a região próxima ao ponto de equivalência. O indicador apontado pelo sistema representa a melhor opção entre os indicadores cadastrados e avaliados para aquela condição.",
    prioridade: 10,
  },
  {
    id: "complexometria_interferente_conceito",
    modulo: "complexometria",
    topico: "Interferente",
    assunto: "interferente",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é interferente?",
      "O que é metal interferente?",
      "O que atrapalha a titulação com EDTA?",
    ],
    palavrasChave: [
      "interferente",
      "metal interferente",
      "interferência",
      "interferencia",
      "competição pelo edta",
      "competicao pelo edta",
    ],
    termosContexto: [
      "interferentes avaliados",
      "risco de interferência",
      "metal principal",
      "Kf efetivo do interferente",
    ],
    termosEvitar: ["mascarante", "complexante auxiliar", "indicador"],
    respostaCurta:
      "Interferentes são espécies que podem competir com o metal principal pelo EDTA ou alterar o equilíbrio da titulação.",
    respostaCompleta:
      "Na complexometria, um interferente pode reagir com o EDTA, consumir parte do titulante, modificar a disponibilidade do metal principal ou afetar a detecção do ponto final. Seu impacto depende da afinidade pelo EDTA, da concentração e das condições do meio.",
    prioridade: 10,
  },
  {
    id: "geral_titulado_conceito",
    modulo: "geral",
    topico: "Titulado",
    assunto: "titulado",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é titulado?",
      "O que é solução titulada?",
      "Quem recebe o titulante?",
    ],
    palavrasChave: [
      "titulado",
      "solução titulada",
      "solucao titulada",
      "amostra titulada",
      "solução analisada",
      "solucao analisada",
      "quem recebe o titulante",
      "conteúdo do erlenmeyer",
      "conteudo do erlenmeyer",
    ],
    termosContexto: ["titulado", "amostra", "analito", "titulante"],
    termosEvitar: ["titulante", "indicador", "interferente"],
    respostaCurta:
      "Titulado é a solução que contém a espécie que será analisada na titulação.",
    respostaCompleta:
      "O titulado é a solução que recebe o titulante durante a titulação. Normalmente, ele contém o analito, ou seja, a espécie cuja quantidade ou concentração se deseja determinar. Em muitos procedimentos, o titulado fica no erlenmeyer ou no recipiente de reação.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_equivalencia_conceito",
    modulo: "geral",
    topico: "Ponto de equivalência",
    assunto: "ponto_equivalencia",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é ponto de equivalência?",
      "O que significa PE?",
      "O que é equivalência na titulação?",
    ],
    palavrasChave: [
      "ponto de equivalência",
      "ponto de equivalencia",
      "pe da titulação",
      "pe da titulacao",
      "equivalência",
      "equivalencia",
      "condição estequiométrica",
      "condicao estequiometrica",
    ],
    termosContexto: [
      "ponto de equivalência",
      "volume de equivalência",
      "estequiometria",
      "titulante",
      "analito",
    ],
    termosEvitar: [
      "ponto final",
      "indicador",
      "pH no PE",
      "complexometria",
      "ácido-base",
      "acido-base",
    ],
    respostaCurta:
      "Ponto de equivalência é a condição em que titulante e analito estão nas quantidades previstas pela estequiometria da reação.",
    respostaCompleta:
      "O ponto de equivalência é uma condição teórica da titulação. Ele ocorre quando a quantidade de titulante adicionada corresponde exatamente à quantidade necessária para reagir com o analito segundo a estequiometria da reação. Ele não depende, necessariamente, da mudança visual do indicador.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_final_conceito",
    modulo: "geral",
    topico: "Ponto final",
    assunto: "ponto_final",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é ponto final?",
      "O que é ponto final da titulação?",
      "Quando eu paro a titulação?",
    ],
    palavrasChave: [
      "ponto final",
      "ponto final da titulação",
      "ponto final da titulacao",
      "momento de parar",
      "fim da titulação",
      "fim da titulacao",
      "mudança observada",
      "mudanca observada",
      "sinal experimental",
    ],
    termosContexto: ["ponto final", "indicador", "mudança de cor", "sinal instrumental"],
    termosEvitar: ["ponto de equivalência", "ponto de equivalencia"],
    respostaCurta:
      "Ponto final é o sinal experimental usado para encerrar a titulação.",
    respostaCompleta:
      "O ponto final é o momento identificado experimentalmente para encerrar a titulação. Ele pode ser observado por mudança de cor, resposta instrumental ou outro sinal definido pelo método. O ideal é que o ponto final ocorra o mais próximo possível do ponto de equivalência.",
    prioridade: 10,
  },
  {
    id: "geral_ponto_final_equivalencia_relacao",
    modulo: "geral",
    topico: "Ponto final e ponto de equivalência",
    assunto: "ponto_final_equivalencia",
    intencao: "comparacao",
    perguntasExemplo: [
      "Qual a diferença entre ponto final e ponto de equivalência?",
      "Ponto final é igual ao ponto de equivalência?",
      "Qual a diferença entre PE e ponto final?",
    ],
    palavrasChave: [
      "diferença entre ponto final e ponto de equivalência",
      "diferenca entre ponto final e ponto de equivalencia",
      "ponto final versus pe",
      "ponto final vs ponto de equivalência",
      "ponto final é igual ao pe",
      "ponto final e equivalência",
      "ponto final e equivalencia",
    ],
    termosContexto: ["ponto final", "ponto de equivalência", "indicador", "erro de titulação"],
    termosEvitar: ["volume de equivalência", "calcular PE"],
    respostaCurta:
      "O ponto de equivalência é teórico e estequiométrico; o ponto final é o sinal experimental observado.",
    respostaCompleta:
      "O ponto de equivalência corresponde à condição química ideal definida pela estequiometria da reação. Já o ponto final é o sinal observado na prática, como uma mudança de cor do indicador. Um bom método busca fazer o ponto final ocorrer o mais próximo possível do ponto de equivalência, reduzindo o erro de titulação.",
    prioridade: 10,
  },
  {
    id: "geral_curva_titulacao_conceito",
    modulo: "geral",
    topico: "Curva de titulação",
    assunto: "curva",
    intencao: "conceito",
    perguntasExemplo: [
      "O que representa a curva de titulação?",
      "O que é curva de titulação?",
      "Como interpretar uma curva de titulação?",
    ],
    palavrasChave: [
      "curva de titulação",
      "curva de titulacao",
      "gráfico da titulação",
      "grafico da titulacao",
      "propriedade versus volume",
      "volume de titulante",
      "curva volumétrica",
      "curva volumetrica",
    ],
    termosContexto: ["curva", "volume de titulante", "ponto de equivalência"],
    termosEvitar: [
      "curva ácido-base",
      "curva acido-base",
      "curva complexométrica",
      "curva complexometrica",
      "pM",
      "pH",
    ],
    respostaCurta:
      "A curva de titulação mostra como uma propriedade da solução varia conforme o titulante é adicionado.",
    respostaCompleta:
      "A curva de titulação representa a variação de uma propriedade do sistema em função do volume de titulante adicionado. Essa propriedade pode ser pH, pM, potencial ou outro sinal analítico, dependendo do tipo de titulação. A curva ajuda a visualizar regiões antes, próximas e depois do ponto de equivalência.",
    prioridade: 9,
  },
  {
    id: "geral_indicador_conceito",
    modulo: "geral",
    topico: "Indicador",
    assunto: "indicador",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é indicador?",
      "Para que serve um indicador?",
      "O que é indicador de titulação?",
    ],
    palavrasChave: [
      "indicador",
      "indicador químico",
      "indicador quimico",
      "indicador de titulação",
      "indicador de titulacao",
      "substância que muda de cor",
      "substancia que muda de cor",
      "função do indicador",
      "funcao do indicador",
    ],
    termosContexto: ["indicador", "ponto final", "mudança de cor"],
    termosEvitar: [
      "indicador complexométrico",
      "indicador complexometrico",
      "indicador ácido-base",
      "indicador acido-base",
      "qual indicador devo usar",
      "melhor indicador",
    ],
    respostaCurta:
      "Indicador é uma substância ou sistema que produz um sinal perceptível próximo ao ponto final da titulação.",
    respostaCompleta:
      "Um indicador é utilizado para sinalizar uma mudança importante durante a titulação, geralmente próxima ao ponto final. Em muitos casos, esse sinal é uma mudança de cor. A escolha do indicador depende do tipo de reação e da região em que se deseja detectar o final da titulação.",
    prioridade: 9,
  },
  {
    id: "geral_concentracao_molar_conceito",
    modulo: "geral",
    topico: "Concentração molar",
    assunto: "concentracao_molar",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é concentração molar?",
      "O que é molaridade?",
      "O que significa mol por litro?",
    ],
    palavrasChave: [
      "concentração molar",
      "concentracao molar",
      "molaridade",
      "mol por litro",
      "mol/l",
      "mol L",
      "quantidade de matéria por volume",
      "quantidade de materia por volume",
    ],
    termosContexto: ["concentração", "mol/L", "volume", "quantidade de matéria"],
    termosEvitar: [
      "concentração do EDTA",
      "concentracao do EDTA",
      "concentração do metal",
      "concentracao do metal",
      "metal livre",
    ],
    respostaCurta:
      "Concentração molar é a quantidade de matéria do soluto dividida pelo volume da solução em litros.",
    respostaCompleta:
      "A concentração molar, também chamada de molaridade, indica quantos mols de soluto existem em cada litro de solução. Ela é expressa por C = n/V, em que n é a quantidade de matéria em mol e V é o volume da solução em litros. Sua unidade usual é mol/L.",
    prioridade: 10,
  },
  {
    id: "geral_estequiometria_conceito",
    modulo: "geral",
    topico: "Estequiometria",
    assunto: "estequiometria",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é estequiometria?",
      "O que é relação molar?",
      "O que significa proporção entre reagentes?",
    ],
    palavrasChave: [
      "estequiometria",
      "relação molar",
      "relacao molar",
      "proporção entre reagentes",
      "proporcao entre reagentes",
      "coeficientes da equação",
      "coeficientes da equacao",
      "quantidade que reage",
    ],
    termosContexto: ["estequiometria", "equação balanceada", "relação molar"],
    termosEvitar: [
      "estequiometria metal edta",
      "proporção 1 para 1 edta",
      "calcular volume",
    ],
    respostaCurta:
      "Estequiometria é a relação quantitativa entre as espécies que participam de uma reação química.",
    respostaCompleta:
      "A estequiometria descreve a proporção em que reagentes e produtos participam de uma reação química. Em uma equação balanceada, os coeficientes indicam a relação entre os mols das espécies. Em titulações, essa relação permite converter o volume de titulante na quantidade de analito.",
    prioridade: 10,
  },
  {
    id: "geral_volume_equivalencia_conceito",
    modulo: "geral",
    topico: "Volume de equivalência",
    assunto: "volume_equivalencia",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é volume de equivalência?",
      "O que significa volume do PE?",
      "O que é volume necessário para atingir o PE?",
    ],
    palavrasChave: [
      "volume de equivalência",
      "volume de equivalencia",
      "volume do pe",
      "volume pe",
      "volume necessário",
      "volume necessario",
      "volume estequiométrico",
      "volume estequiometrico",
    ],
    termosContexto: ["volume de equivalência", "titulante", "ponto de equivalência"],
    termosEvitar: [
      "ponto final",
      "curva",
      "volume da amostra",
      "volume total",
    ],
    respostaCurta:
      "Volume de equivalência é o volume de titulante necessário para atingir o ponto de equivalência.",
    respostaCompleta:
      "O volume de equivalência corresponde ao volume de titulante necessário para reagir estequiometricamente com o analito presente na amostra. Ele depende da quantidade de analito, da concentração do titulante e da proporção da reação.",
    prioridade: 10,
  },
  {
    id: "geral_erro_titulacao_conceito",
    modulo: "geral",
    topico: "Erro de titulação",
    assunto: "erro_titulacao",
    intencao: "conceito",
    perguntasExemplo: [
      "O que é erro de titulação?",
      "O que causa erro em uma titulação?",
      "Por que o resultado da titulação pode dar errado?",
    ],
    palavrasChave: [
      "erro de titulação",
      "erro de titulacao",
      "erro experimental",
      "erro analítico",
      "erro analitico",
      "resultado errado",
      "causas de erro",
    ],
    termosContexto: ["ponto final", "ponto de equivalência", "indicador", "volume"],
    termosEvitar: [
      "erro na complexometria",
      "erro ácido-base",
      "erro acido-base",
      "sistema não aceita valor",
      "campo inválido",
    ],
    respostaCurta:
      "Erro de titulação é a diferença entre o resultado obtido e o valor esperado ou verdadeiro.",
    respostaCompleta:
      "O erro de titulação pode surgir por diferença entre ponto final e ponto de equivalência, leitura incorreta do volume, preparo inadequado das soluções, escolha ruim do indicador, contaminação, perdas de amostra ou falhas no procedimento. Reduzir esses erros aumenta a confiabilidade da análise.",
    prioridade: 9,
  },
  {
    id: "geral_unidades_conceito",
    modulo: "geral",
    topico: "Unidades",
    assunto: "unidades",
    intencao: "conceito",
    perguntasExemplo: [
      "Quais unidades devo usar?",
      "A concentração é em mol por litro?",
      "O volume é em mL ou L?",
    ],
    palavrasChave: [
      "unidades",
      "quais unidades",
      "mol por litro",
      "mol/l",
      "ml",
      "l",
      "litro",
      "mililitro",
      "unidade de volume",
      "unidade de concentração",
      "unidade de concentracao",
    ],
    termosContexto: ["mol/L", "mL", "L", "concentração", "volume"],
    termosEvitar: [
      "misturei ml e l",
      "erro de conversão",
      "resultado mil vezes",
    ],
    respostaCurta:
      "As unidades devem seguir exatamente o que cada campo da interface solicita.",
    respostaCompleta:
      "Em geral, concentrações molares são expressas em mol/L, enquanto volumes podem ser informados em mL ou L, dependendo do campo. É importante seguir a unidade indicada pela interface, porque uma conversão incorreta pode alterar muito o resultado.",
    prioridade: 9,
  },
  {
    id: "geral_arredondamento_conceito",
    modulo: "geral",
    topico: "Arredondamento",
    assunto: "arredondamento",
    intencao: "conceito",
    perguntasExemplo: [
      "Por que os valores aparecem arredondados?",
      "Por que o valor exibido tem poucas casas decimais?",
      "O sistema usa mais casas decimais internamente?",
    ],
    palavrasChave: [
      "arredondamento",
      "valores arredondados",
      "casas decimais",
      "valor aproximado",
      "precisão exibida",
      "precisao exibida",
      "valor interno",
    ],
    termosContexto: ["resultado exibido", "casas decimais", "valor interno"],
    termosEvitar: [
      "erro grande",
      "falha no código",
      "falha no codigo",
      "unidade errada",
    ],
    respostaCurta:
      "O sistema pode exibir valores arredondados para facilitar a leitura dos resultados.",
    respostaCompleta:
      "O arredondamento reduz a quantidade de casas decimais mostradas na interface e torna os resultados mais legíveis. Em alguns casos, o cálculo interno pode usar mais precisão do que o valor exibido. Por isso, pequenas diferenças podem aparecer por arredondamento, sem indicar erro no cálculo.",
    prioridade: 8,
  },
];